# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Modularity1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Modularity1

pod 'Alamofire'
pod 'SwiftyJSON','~> 4.0'


end
